# Matrix directionality: source on node-2 relayed to node-1.
name: reverse
enabled: true
source:
  srt:
    node: strom-node-2
    latency: 200
destinations:
  - srt:
      node: strom-node-1
      latency: 1000
